/*
 * DSP Data Injector Simulator
 *
 * Generates synthetic SP detection messages simulating drone targets
 * and publishes them on the DDS topic "SPDetection" (domain 0).
 * The message type is CounterUAS::SPDetectionMessage, generated by
 * fastddsgen from idl/messages.idl.
 *
 * Radar specs (per antenna wall, 4 walls): Azimuth FoV ±60°, Elevation FoV 90°,
 * Range accuracy 1 m, Angular accuracy 0.3° (az/el), Max range 30 km.
 *
 * Usage: dsp_injector [num_targets] [duration_sec] [rate_ms]
 */

#include "common/types.h"
#include "common/dds_participant.h"
#include "common/constants.h"
#include "common/logger.h"

#include <fastdds/dds/publisher/DataWriter.hpp>

#include <algorithm>
#include <iostream>
#include <cmath>
#include <random>
#include <chrono>
#include <thread>
#include <vector>
#include <string>
#include <csignal>
#include <atomic>

static std::atomic<bool> g_running{true};
void signalHandler(int) { g_running.store(false); }

namespace RadarSpecs {
    constexpr double AZ_HALF_FOV_RAD    = 60.0 * cuas::DEG2RAD;
    constexpr double EL_FOV_MAX_RAD     = 90.0 * cuas::DEG2RAD;
    constexpr double EL_FOV_MIN_RAD     = 0.0;
    constexpr double RANGE_ACCURACY_M   = 1.0;
    constexpr double ANGULAR_ACCURACY_RAD = 0.3 * cuas::DEG2RAD;
    constexpr double MAX_RANGE_M        = 30000.0;
}

struct SimTarget {
    double range, azimuth, elevation;
    double speed, heading, climbRate, turnRate;
    double rcs, microDoppler;
    bool   active;
};

class DSPSimulator {
public:
    DSPSimulator(int numTargets, double noiseFloor, unsigned seed)
        : rng_(seed), noiseFloor_(noiseFloor) {
        initTargets(numTargets);
    }

    void initTargets(int n) {
        std::uniform_real_distribution<> rangeDist(500.0, std::min(8000.0, RadarSpecs::MAX_RANGE_M - 500.0));
        std::uniform_real_distribution<> azDist(-RadarSpecs::AZ_HALF_FOV_RAD, RadarSpecs::AZ_HALF_FOV_RAD);
        std::uniform_real_distribution<> elDist(RadarSpecs::EL_FOV_MIN_RAD + 0.02, RadarSpecs::EL_FOV_MAX_RAD * 0.5);
        std::uniform_real_distribution<> speedDist(5.0, 40.0);
        std::uniform_real_distribution<> headingDist(-cuas::PI, cuas::PI);
        std::uniform_real_distribution<> turnDist(-0.05, 0.05);
        std::uniform_real_distribution<> rcsDist(-15.0, 5.0);
        std::uniform_real_distribution<> microDist(50.0, 500.0);

        targets_.clear();
        for (int i = 0; i < n; ++i) {
            SimTarget t;
            t.range        = rangeDist(rng_);
            t.azimuth      = azDist(rng_);
            t.elevation    = elDist(rng_);
            t.speed        = speedDist(rng_);
            t.heading      = headingDist(rng_);
            t.climbRate    = 0.5;
            t.turnRate     = turnDist(rng_);
            t.rcs          = rcsDist(rng_);
            t.microDoppler = microDist(rng_);
            t.active       = true;
            targets_.push_back(t);
        }
    }

    void updateTargets(double dt) {
        std::normal_distribution<> accelNoise(0.0, 0.5);
        std::normal_distribution<> turnNoise(0.0, 0.005);

        for (auto& t : targets_) {
            if (!t.active) continue;

            double x = t.range * std::cos(t.elevation) * std::cos(t.azimuth);
            double y = t.range * std::cos(t.elevation) * std::sin(t.azimuth);
            double z = t.range * std::sin(t.elevation);

            x += t.speed * std::cos(t.heading) * dt;
            y += t.speed * std::sin(t.heading) * dt;
            z += t.climbRate * dt;

            t.heading   += t.turnRate * dt + turnNoise(rng_) * dt;
            t.speed     += accelNoise(rng_) * dt;
            t.climbRate += accelNoise(rng_) * 0.1 * dt;

            if (t.speed < 2.0)  t.speed = 2.0;
            if (t.speed > 60.0) t.speed = 60.0;
            if (z < 10.0)    { z = 10.0;    t.climbRate =  std::abs(t.climbRate); }
            if (z > 3000.0)  { t.climbRate = -std::abs(t.climbRate); }

            t.range     = std::sqrt(x*x + y*y + z*z);
            t.azimuth   = std::atan2(y, x);
            t.elevation = std::asin(z / std::max(t.range, 1.0));

            if (t.range > RadarSpecs::MAX_RANGE_M || t.range < 30.0)
                t.active = false;
            if (t.azimuth < -RadarSpecs::AZ_HALF_FOV_RAD ||
                t.azimuth >  RadarSpecs::AZ_HALF_FOV_RAD)
                t.active = false;
            if (t.elevation < RadarSpecs::EL_FOV_MIN_RAD ||
                t.elevation > RadarSpecs::EL_FOV_MAX_RAD)
                t.active = false;
        }
    }

    // Build an IDL-typed SPDetectionMessage — no hand-rolled serialization.
    CounterUAS::SPDetectionMessage generateDwell(uint32_t dwellCount) {
        CounterUAS::SPDetectionMessage msg;
        msg.messageId(cuas::MSG_ID_SP_DETECTION);
        msg.dwellCount(dwellCount);
        msg.timestamp(cuas::nowMicros());

        std::normal_distribution<> rangeNoise(0.0,  RadarSpecs::RANGE_ACCURACY_M);
        std::normal_distribution<> azNoise(0.0,     RadarSpecs::ANGULAR_ACCURACY_RAD);
        std::normal_distribution<> elNoise(0.0,     RadarSpecs::ANGULAR_ACCURACY_RAD);
        std::normal_distribution<> strNoise(0.0,    3.0);
        std::uniform_int_distribution<> numFalseAlarms(0, 3);
        std::uniform_real_distribution<> probDetect(0.0, 1.0);
        std::uniform_int_distribution<> extraDets(0, 2);

        std::vector<CounterUAS::DetectionData> dets;

        // Target returns
        for (const auto& t : targets_) {
            if (!t.active) continue;

            double pd = 0.95 - (t.range / RadarSpecs::MAX_RANGE_M);
            if (probDetect(rng_) > pd) continue;

            CounterUAS::DetectionData det;
            det.range(std::max(0.0, std::min(RadarSpecs::MAX_RANGE_M,
                               t.range + rangeNoise(rng_))));
            det.azimuth(std::max(-RadarSpecs::AZ_HALF_FOV_RAD,
                         std::min( RadarSpecs::AZ_HALF_FOV_RAD,
                                   t.azimuth + azNoise(rng_))));
            det.elevation(std::max(RadarSpecs::EL_FOV_MIN_RAD,
                           std::min(RadarSpecs::EL_FOV_MAX_RAD,
                                    t.elevation + elNoise(rng_))));
            det.rcs(t.rcs + strNoise(rng_) * 0.5);
            det.microDoppler(t.microDoppler + strNoise(rng_) * 10.0);

            double pathLoss = 40.0 * std::log10(std::max(det.range(), 1.0));
            det.strength(-30.0 + det.rcs() - pathLoss + 100.0 + strNoise(rng_));
            det.noise(noiseFloor_ + strNoise(rng_) * 0.5);
            det.snr(det.strength() - det.noise());

            int numDets = 1 + extraDets(rng_);
            for (int d = 0; d < numDets; ++d) {
                CounterUAS::DetectionData extra = det;
                if (d > 0) {
                    extra.range(std::max(0.0, std::min(RadarSpecs::MAX_RANGE_M,
                                extra.range() + rangeNoise(rng_) * 2.0)));
                    extra.azimuth(std::max(-RadarSpecs::AZ_HALF_FOV_RAD,
                                  std::min( RadarSpecs::AZ_HALF_FOV_RAD,
                                            extra.azimuth() + azNoise(rng_) * 2.0)));
                    extra.elevation(std::max(RadarSpecs::EL_FOV_MIN_RAD,
                                    std::min(RadarSpecs::EL_FOV_MAX_RAD,
                                             extra.elevation() + elNoise(rng_) * 2.0)));
                    extra.strength(extra.strength() - 3.0 - std::abs(strNoise(rng_)));
                    extra.snr(extra.strength() - extra.noise());
                }
                dets.push_back(extra);
            }
        }

        // False alarms
        int nFA = numFalseAlarms(rng_);
        std::uniform_real_distribution<> faRange(100.0, RadarSpecs::MAX_RANGE_M);
        std::uniform_real_distribution<> faAz(-RadarSpecs::AZ_HALF_FOV_RAD, RadarSpecs::AZ_HALF_FOV_RAD);
        std::uniform_real_distribution<> faEl(RadarSpecs::EL_FOV_MIN_RAD, RadarSpecs::EL_FOV_MAX_RAD * 0.5);

        for (int i = 0; i < nFA; ++i) {
            CounterUAS::DetectionData fa;
            fa.range(faRange(rng_));      fa.azimuth(faAz(rng_));  fa.elevation(faEl(rng_));
            fa.strength(noiseFloor_ + 5.0 + strNoise(rng_));
            fa.noise(noiseFloor_);        fa.snr(fa.strength() - fa.noise());
            fa.rcs(-20.0 + strNoise(rng_));
            fa.microDoppler(strNoise(rng_) * 5.0);
            dets.push_back(fa);
        }

        msg.numDetections(static_cast<uint32_t>(dets.size()));
        msg.detections(dets);
        return msg;
    }

    int activeTargets() const {
        int c = 0;
        for (const auto& t : targets_) if (t.active) ++c;
        return c;
    }

private:
    std::mt19937 rng_;
    double noiseFloor_;
    std::vector<SimTarget> targets_;
};

int main(int argc, char* argv[]) {
    int numTargets  = 1;
    int durationSec = 60;
    int rateMs      = 100;

    if (argc > 1) numTargets  = std::stoi(argv[1]);
    if (argc > 2) durationSec = std::stoi(argv[2]);
    if (argc > 3) rateMs      = std::stoi(argv[3]);

    std::signal(SIGINT,  signalHandler);
#ifndef _WIN32
    std::signal(SIGTERM, signalHandler);
#endif

    cuas::ConsoleLogger::instance().setLevel(cuas::ConsoleLogger::INFO);

    std::cerr <<
        "================================================================\n"
        "  DSP Data Injector Simulator (DDS)\n"
        "  Topic: " << cuas::TOPIC_SP_DETECTION << "  Domain: 0\n"
        "  Targets: " << numTargets << "  Duration: " << durationSec << "s"
        "  Rate: " << rateMs << "ms\n"
        "================================================================\n";

    // One DDS participant publishes on "SPDetection".
    cuas::CuasDdsParticipant participant;
    auto* writer = participant.makeWriter<CounterUAS::SPDetectionMessage>(
                       cuas::TOPIC_SP_DETECTION);

    unsigned seed = static_cast<unsigned>(
        std::chrono::steady_clock::now().time_since_epoch().count());
    DSPSimulator sim(numTargets, -90.0, seed);

    double   dt         = rateMs * 0.001;
    uint32_t dwellCount = 0;
    auto startTime = std::chrono::steady_clock::now();

    while (g_running.load()) {
        auto elapsed = std::chrono::steady_clock::now() - startTime;
        if (std::chrono::duration_cast<std::chrono::seconds>(elapsed).count() >= durationSec)
            break;

        sim.updateTargets(dt);
        auto msg = sim.generateDwell(dwellCount);

        // DDS write — CDR serialization is handled by the generated PubSubType.
        writer->write(&msg);

        if (dwellCount % 50 == 0) {
            LOG_INFO("DSPInjector", "Dwell %u: %u detections, %d active targets",
                     dwellCount, msg.numDetections(), sim.activeTargets());
        }

        ++dwellCount;
        std::this_thread::sleep_for(std::chrono::milliseconds(rateMs));
    }

    LOG_INFO("DSPInjector", "Finished. Total dwells: %u", dwellCount);
    return 0;
}
